2025-09-27 04:54:00,869 ERROR scheduler Skipped queueing frappe.model.utils.user_settings.sync_user_settings because it was found in queue for library.localhost
2025-09-27 04:54:00,872 ERROR scheduler Skipped queueing frappe.desk.page.backups.backups.delete_downloadable_backups because it was found in queue for library.localhost
2025-09-27 04:54:00,873 ERROR scheduler Skipped queueing frappe.desk.utils.delete_old_exported_report_files because it was found in queue for library.localhost
2025-09-27 04:54:00,874 ERROR scheduler Skipped queueing frappe.oauth.delete_oauth2_data because it was found in queue for library.localhost
2025-09-27 04:54:00,875 ERROR scheduler Skipped queueing frappe.website.doctype.personal_data_deletion_request.personal_data_deletion_request.process_data_deletion_request because it was found in queue for library.localhost
2025-09-27 14:10:00,313 ERROR scheduler Skipped queueing frappe.deferred_insert.save_to_db because it was found in queue for library.localhost
2025-09-27 14:10:00,314 ERROR scheduler Skipped queueing frappe.model.utils.link_count.update_link_count because it was found in queue for library.localhost
2025-09-27 14:10:00,314 ERROR scheduler Skipped queueing frappe.email.doctype.email_account.email_account.notify_unreplied because it was found in queue for library.localhost
2025-09-27 14:10:00,315 ERROR scheduler Skipped queueing frappe.email.queue.flush because it was found in queue for library.localhost
2025-09-27 14:10:00,315 ERROR scheduler Skipped queueing frappe.monitor.flush because it was found in queue for library.localhost
2025-09-27 14:10:00,315 ERROR scheduler Skipped queueing frappe.email.queue.retry_sending_emails because it was found in queue for library.localhost
2025-09-27 14:10:00,316 ERROR scheduler Skipped queueing frappe.email.doctype.notification.notification.trigger_offset_alerts because it was found in queue for library.localhost
2025-09-27 14:10:00,316 ERROR scheduler Skipped queueing frappe.search.sqlite_search.build_index_if_not_exists because it was found in queue for library.localhost
2025-09-27 14:10:00,316 ERROR scheduler Skipped queueing frappe.pulse.client.send_queued_events because it was found in queue for library.localhost
2025-09-27 20:38:00,210 ERROR scheduler Exception in Enqueue Events for Site library.localhost
Traceback (most recent call last):
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/connection.py", line 622, in can_read
    return self._parser.can_read(timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/_parsers/hiredis.py", line 99, in can_read
    return self.read_from_socket(timeout=timeout, raise_on_timeout=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/_parsers/hiredis.py", line 108, in read_from_socket
    bufflen = self._sock.recv_into(self._buffer)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/connection.py", line 1536, in get_connection
    if connection.can_read() and self.cache is None:
       ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/connection.py", line 625, in can_read
    raise ConnectionError(f"Error while reading from {host_error}: {e.args}")
redis.exceptions.ConnectionError: Error while reading from 127.0.0.1:11000: (54, 'Connection reset by peer')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/connection.py", line 385, in connect_check_health
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/retry.py", line 87, in call_with_retry
    return do()
           ^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/connection.py", line 386, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/connection.py", line 797, in _connect
    raise err
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/connection.py", line 781, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 120, in enqueue_events_for_site
    enqueue_events()
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 140, in enqueue_events
    if job_type.enqueue():
       ^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 74, in enqueue
    if not self.is_job_in_queue():
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 96, in is_job_in_queue
    return is_job_enqueued(self.rq_job_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 665, in is_job_enqueued
    return get_job_status(job_id) in (JobStatus.QUEUED, JobStatus.STARTED)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 670, in get_job_status
    if job := get_job(job_id):
              ^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 676, in get_job
    return Job.fetch(create_job_id(job_id), connection=get_redis_conn())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/rq/job.py", line 674, in fetch
    job.refresh()
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/rq/job.py", line 1037, in refresh
    data = self.connection.hgetall(self.key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/commands/core.py", line 4959, in hgetall
    return self.execute_command("HGETALL", name, keys=[name])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/client.py", line 623, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/client.py", line 629, in _execute_command
    conn = self.connection or pool.get_connection()
                              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/utils.py", line 191, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/connection.py", line 1540, in get_connection
    connection.connect()
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/connection.py", line 379, in connect
    self.connect_check_health(check_health=True)
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/connection.py", line 391, in connect_check_health
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to 127.0.0.1:11000. Connection refused.
2025-09-27 20:42:00,321 ERROR scheduler Exception in Enqueue Events for Site library.localhost
Traceback (most recent call last):
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/connection.py", line 385, in connect_check_health
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/retry.py", line 87, in call_with_retry
    return do()
           ^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/connection.py", line 386, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/connection.py", line 797, in _connect
    raise err
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/connection.py", line 781, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 120, in enqueue_events_for_site
    enqueue_events()
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 140, in enqueue_events
    if job_type.enqueue():
       ^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 74, in enqueue
    if not self.is_job_in_queue():
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 96, in is_job_in_queue
    return is_job_enqueued(self.rq_job_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 665, in is_job_enqueued
    return get_job_status(job_id) in (JobStatus.QUEUED, JobStatus.STARTED)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 670, in get_job_status
    if job := get_job(job_id):
              ^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 676, in get_job
    return Job.fetch(create_job_id(job_id), connection=get_redis_conn())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/rq/job.py", line 674, in fetch
    job.refresh()
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/rq/job.py", line 1037, in refresh
    data = self.connection.hgetall(self.key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/commands/core.py", line 4959, in hgetall
    return self.execute_command("HGETALL", name, keys=[name])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/client.py", line 623, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/client.py", line 629, in _execute_command
    conn = self.connection or pool.get_connection()
                              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/utils.py", line 191, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/connection.py", line 1530, in get_connection
    connection.connect()
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/connection.py", line 379, in connect
    self.connect_check_health(check_health=True)
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/connection.py", line 391, in connect_check_health
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to 127.0.0.1:11000. Connection refused.
2025-09-27 20:50:00,525 ERROR scheduler Exception in Enqueue Events for Site library.localhost
Traceback (most recent call last):
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/connection.py", line 622, in can_read
    return self._parser.can_read(timeout)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/_parsers/hiredis.py", line 99, in can_read
    return self.read_from_socket(timeout=timeout, raise_on_timeout=False)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/_parsers/hiredis.py", line 108, in read_from_socket
    bufflen = self._sock.recv_into(self._buffer)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/connection.py", line 1536, in get_connection
    if connection.can_read() and self.cache is None:
       ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/connection.py", line 625, in can_read
    raise ConnectionError(f"Error while reading from {host_error}: {e.args}")
redis.exceptions.ConnectionError: Error while reading from 127.0.0.1:11000: (54, 'Connection reset by peer')

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/connection.py", line 385, in connect_check_health
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/retry.py", line 87, in call_with_retry
    return do()
           ^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/connection.py", line 386, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/connection.py", line 797, in _connect
    raise err
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/connection.py", line 781, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 120, in enqueue_events_for_site
    enqueue_events()
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 140, in enqueue_events
    if job_type.enqueue():
       ^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 74, in enqueue
    if not self.is_job_in_queue():
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 96, in is_job_in_queue
    return is_job_enqueued(self.rq_job_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 665, in is_job_enqueued
    return get_job_status(job_id) in (JobStatus.QUEUED, JobStatus.STARTED)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 670, in get_job_status
    if job := get_job(job_id):
              ^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 676, in get_job
    return Job.fetch(create_job_id(job_id), connection=get_redis_conn())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/rq/job.py", line 674, in fetch
    job.refresh()
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/rq/job.py", line 1037, in refresh
    data = self.connection.hgetall(self.key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/commands/core.py", line 4959, in hgetall
    return self.execute_command("HGETALL", name, keys=[name])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/client.py", line 623, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/client.py", line 629, in _execute_command
    conn = self.connection or pool.get_connection()
                              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/utils.py", line 191, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/connection.py", line 1540, in get_connection
    connection.connect()
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/connection.py", line 379, in connect
    self.connect_check_health(check_health=True)
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/connection.py", line 391, in connect_check_health
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to 127.0.0.1:11000. Connection refused.
2025-09-27 20:54:00,611 ERROR scheduler Exception in Enqueue Events for Site library.localhost
Traceback (most recent call last):
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/connection.py", line 385, in connect_check_health
    sock = self.retry.call_with_retry(
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/retry.py", line 87, in call_with_retry
    return do()
           ^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/connection.py", line 386, in <lambda>
    lambda: self._connect(), lambda error: self.disconnect(error)
            ^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/connection.py", line 797, in _connect
    raise err
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/connection.py", line 781, in _connect
    sock.connect(socket_address)
ConnectionRefusedError: [Errno 61] Connection refused

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 120, in enqueue_events_for_site
    enqueue_events()
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/apps/frappe/frappe/utils/scheduler.py", line 140, in enqueue_events
    if job_type.enqueue():
       ^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 74, in enqueue
    if not self.is_job_in_queue():
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/apps/frappe/frappe/core/doctype/scheduled_job_type/scheduled_job_type.py", line 96, in is_job_in_queue
    return is_job_enqueued(self.rq_job_id)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 665, in is_job_enqueued
    return get_job_status(job_id) in (JobStatus.QUEUED, JobStatus.STARTED)
           ^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 670, in get_job_status
    if job := get_job(job_id):
              ^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/apps/frappe/frappe/utils/background_jobs.py", line 676, in get_job
    return Job.fetch(create_job_id(job_id), connection=get_redis_conn())
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/rq/job.py", line 674, in fetch
    job.refresh()
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/rq/job.py", line 1037, in refresh
    data = self.connection.hgetall(self.key)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/commands/core.py", line 4959, in hgetall
    return self.execute_command("HGETALL", name, keys=[name])
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/client.py", line 623, in execute_command
    return self._execute_command(*args, **options)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/client.py", line 629, in _execute_command
    conn = self.connection or pool.get_connection()
                              ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/utils.py", line 191, in wrapper
    return func(*args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/connection.py", line 1530, in get_connection
    connection.connect()
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/connection.py", line 379, in connect
    self.connect_check_health(check_health=True)
  File "/Users/apple/Desktop/LearningFrappe/frappe-bench/env/lib/python3.12/site-packages/redis/connection.py", line 391, in connect_check_health
    raise ConnectionError(self._error_message(e))
redis.exceptions.ConnectionError: Error 61 connecting to 127.0.0.1:11000. Connection refused.
